# Generated by Django 2.2.5 on 2020-01-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_description',
        ),
    ]
