# Generated by Django 2.2.5 on 2020-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_food_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
